name: flutter_project_frame
description: flutter项目脚手架
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # connectivity_plus 检查网络连接  https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^4.0.2
  # internet_connection_checker 检查网络连接  https://pub:dev/packages/internet_connection_checker:
  internet_connection_checker: ^1.0.0+1

  # flutter_nb_net 网络请求以及相关的缓存库 https://pub.dev/packages/flutter_nb_net/install
  flutter_nb_net: ^2.0.2
  dio_cache_interceptor: ^3.4.2
  dio_cookie_manager: ^3.1.0
  dio_http_cache_lts: ^0.4.1

  # GetX 状态管理、路由、国际化、主题框架库，https://pub.dev/packages/get#state-management
  get: ^4.6.5

  # flutter_screenutil 屏幕适配，https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.9.0

  # permission_handler 权限管理，https://pub.dev/packages/permission_handler
  permission_handler: ^10.4.3

  # cached_network_image 图片缓存，https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.2.3

  # shared_preferences 持久化存储，https://pub.dev/packages/shared_preferences
  synchronized: ^3.1.0
  shared_preferences: ^2.2.0

  # decimal、rational 数据格式化处理 https://pub.dev/packages/decimal    https://pub.dev/packages/rational
  decimal: ^2.3.3
  rational: ^2.2.2

  # isar 数据库，https://pub.dev/packages/isar    isar_flutter_libs，https://pub.dev/packages/isar_flutter_libs   获取文件路径：path_provider
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.0

  # flutter_smart_dialog 万能dialog，https://pub-web.flutter-io.cn/packages/flutter_smart_dialog/install
  flutter_smart_dialog: ^4.9.4

  # bruno: UI组件库 https://gitee.com/mirrors/Bruno#%E6%8E%A5%E5%85%A5
  bruno: ^3.4.0

  # flutter_inappwebview  webview库  https://pub.dev/packages/flutter_inappwebview
  flutter_inappwebview: ^5.7.2+3

  # 日志打印框架  https://pub.dev/packages/logger
  logger: ^1.3.0

dependency_overrides:
  # 因为dio_http_cache依赖的dio 和json_annotation是旧版本，以下为解决依赖冲突的方法
  dio: ^5.0.3
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # 自动生成 isar数据库、表相关文件    https://pub.dev/packages/isar_generator     https://pub.dev/packages/build_runner
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/web/
    - assets/images/
    - assets/images/loading/
    - assets/lottie/

